
animals = [
    {"animal name": "aardvark", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 0,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "antelope", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 0, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "bass", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 0, "fins": 1, "legs": 0, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 4},
    {"animal name": "bear", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 0, "domestic": 0,
     "catsize": 1, "type": 1},
    {"animal name": "boar", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 0,
     "catsize": 1, "type": 1},
    {"animal name": "buffalo", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 0, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "calf", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 0,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 1,
     "catsize": 1, "type": 1},
    {"animal name": "carp", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1, "predator": 0,
     "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 0, "fins": 1, "legs": 0, "tail": 1, "domestic": 1,
     "catsize": 0, "type": 4},
    {"animal name": "catfish", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 0, "fins": 1, "legs": 0, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 4},
    {"animal name": "cavy", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 0,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 0, "domestic": 1,
     "catsize": 0, "type": 1},
    {"animal name": "cheetah", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "chicken", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0,
     "predator": 0, "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1,
     "domestic": 1, "catsize": 0, "type": 2},
    {"animal name": "chub", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 0, "fins": 1, "legs": 0, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 4},
    {"animal name": "clam", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 0, "predator": 1,
     "toothed": 0, "backbone": 0, "breathes": 0, "venomous": 0, "fins": 0, "legs": 0, "tail": 0, "domestic": 0,
     "catsize": 0, "type": 7},
    {"animal name": "crab", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1, "predator": 1,
     "toothed": 0, "backbone": 0, "breathes": 0, "venomous": 0, "fins": 0, "legs": 4, "tail": 0, "domestic": 0,
     "catsize": 0, "type": 7},
    {"animal name": "crayfish", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 0, "backbone": 0, "breathes": 0, "venomous": 0, "fins": 0, "legs": 6, "tail": 0,
     "domestic": 0, "catsize": 0, "type": 7},
    {"animal name": "crow", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0, "predator": 1,
     "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 2},
    {"animal name": "deer", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 0,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 0,
     "catsize": 1, "type": 1},
    {"animal name": "dogfish", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 0, "fins": 1, "legs": 0, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 4},
    {"animal name": "dolphin", "hair": 0, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 1, "legs": 0, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "dove", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0, "predator": 0,
     "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1, "domestic": 1,
     "catsize": 0, "type": 2},
    {"animal name": "duck", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 1, "predator": 0,
     "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 2},
    {"animal name": "elephant", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 0, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "flamingo", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0,
     "predator": 0, "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 2},
    {"animal name": "flea", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 0, "predator": 0,
     "toothed": 0, "backbone": 0, "breathes": 1, "venomous": 0, "fins": 0, "legs": 6, "tail": 0, "domestic": 0,
     "catsize": 0, "type": 6},
    {"animal name": "frog", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 0, "domestic": 0,
     "catsize": 0, "type": 5},
    {"animal name": "frog", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 1, "fins": 0, "legs": 4, "tail": 0, "domestic": 0,
     "catsize": 0, "type": 5},
    {"animal name": "fruitbat", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 1, "aquatic": 0,
     "predator": 0, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 1},
    {"animal name": "giraffe", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 0, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "girl", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 0, "domestic": 1,
     "catsize": 1, "type": 1},
    {"animal name": "gnat", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0, "predator": 0,
     "toothed": 0, "backbone": 0, "breathes": 1, "venomous": 0, "fins": 0, "legs": 6, "tail": 0, "domestic": 0,
     "catsize": 0, "type": 6},
    {"animal name": "goat", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 0,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 1,
     "catsize": 1, "type": 1},
    {"animal name": "gorilla", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 0, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 0,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "gull", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 1, "predator": 1,
     "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 2},
    {"animal name": "haddock", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 0, "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 0, "fins": 1, "legs": 0, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 4},
    {"animal name": "hamster", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 0, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 1, "catsize": 0, "type": 1},
    {"animal name": "hare", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 0,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 1},
    {"animal name": "hawk", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0, "predator": 1,
     "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 2},
    {"animal name": "herring", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 0, "fins": 1, "legs": 0, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 4},
    {"animal name": "honeybee", "hair": 1, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0,
     "predator": 0, "toothed": 0, "backbone": 0, "breathes": 1, "venomous": 1, "fins": 0, "legs": 6, "tail": 0,
     "domestic": 1, "catsize": 0, "type": 6},
    {"animal name": "housefly", "hair": 1, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0,
     "predator": 0, "toothed": 0, "backbone": 0, "breathes": 1, "venomous": 0, "fins": 0, "legs": 6, "tail": 0,
     "domestic": 0, "catsize": 0, "type": 6},
    {"animal name": "kiwi", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 0, "predator": 1,
     "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 2},
    {"animal name": "ladybird", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0,
     "predator": 1, "toothed": 0, "backbone": 0, "breathes": 1, "venomous": 0, "fins": 0, "legs": 6, "tail": 0,
     "domestic": 0, "catsize": 0, "type": 6},
    {"animal name": "lark", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0, "predator": 0,
     "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 2},
    {"animal name": "leopard", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "lion", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 0,
     "catsize": 1, "type": 1},
    {"animal name": "lobster", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 0, "backbone": 0, "breathes": 0, "venomous": 0, "fins": 0, "legs": 6, "tail": 0,
     "domestic": 0, "catsize": 0, "type": 7},
    {"animal name": "lynx", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 0,
     "catsize": 1, "type": 1},
    {"animal name": "mink", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 1, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 0,
     "catsize": 1, "type": 1},
    {"animal name": "mole", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 1},
    {"animal name": "mongoose", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "moth", "hair": 1, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0, "predator": 0,
     "toothed": 0, "backbone": 0, "breathes": 1, "venomous": 0, "fins": 0, "legs": 6, "tail": 0, "domestic": 0,
     "catsize": 0, "type": 6},
    {"animal name": "newt", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 5},
    {"animal name": "octopus", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 0, "backbone": 0, "breathes": 0, "venomous": 0, "fins": 0, "legs": 8, "tail": 0,
     "domestic": 0, "catsize": 1, "type": 7},
    {"animal name": "opossum", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 1},
    {"animal name": "oryx", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 0,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 0,
     "catsize": 1, "type": 1},
    {"animal name": "ostrich", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 0,
     "predator": 0, "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 2},
    {"animal name": "parakeet", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0,
     "predator": 0, "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1,
     "domestic": 1, "catsize": 0, "type": 2},
    {"animal name": "penguin", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 2},
    {"animal name": "pheasant", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0,
     "predator": 0, "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 2},
    {"animal name": "pike", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 0, "fins": 1, "legs": 0, "tail": 1, "domestic": 0,
     "catsize": 1, "type": 4},
    {"animal name": "piranha", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 0, "fins": 1, "legs": 0, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 4},
    {"animal name": "pitviper", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 0,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 1, "fins": 0, "legs": 0, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 3},
    {"animal name": "platypus", "hair": 1, "feathers": 0, "eggs": 1, "milk": 1, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "polecat", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "pony", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 0,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 1,
     "catsize": 1, "type": 1},
    {"animal name": "porpoise", "hair": 0, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 1, "legs": 0, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "puma", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 0,
     "catsize": 1, "type": 1},
    {"animal name": "pussycat", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 1, "catsize": 1, "type": 1},
    {"animal name": "raccoon", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "reindeer", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 0, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 1, "catsize": 1, "type": 1},
    {"animal name": "rhea", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 0, "predator": 1,
     "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1, "domestic": 0,
     "catsize": 1, "type": 2},
    {"animal name": "scorpion", "hair": 0, "feathers": 0, "eggs": 0, "milk": 0, "airborne": 0, "aquatic": 0,
     "predator": 1, "toothed": 0, "backbone": 0, "breathes": 1, "venomous": 1, "fins": 0, "legs": 8, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 7},
    {"animal name": "seahorse", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 0, "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 0, "fins": 1, "legs": 0, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 4},
    {"animal name": "seal", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 1, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 1, "legs": 0, "tail": 0, "domestic": 0,
     "catsize": 1, "type": 1},
    {"animal name": "sealion", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 1, "legs": 2, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "seasnake", "hair": 0, "feathers": 0, "eggs": 0, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 1, "fins": 0, "legs": 0, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 3},
    {"animal name": "seawasp", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 0, "backbone": 0, "breathes": 0, "venomous": 1, "fins": 0, "legs": 0, "tail": 0,
     "domestic": 0, "catsize": 0, "type": 7},
    {"animal name": "skimmer", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 1,
     "predator": 1, "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 2},
    {"animal name": "skua", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 1, "predator": 1,
     "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 2},
    {"animal name": "slowworm", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 0,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 0, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 3},
    {"animal name": "slug", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 0, "predator": 0,
     "toothed": 0, "backbone": 0, "breathes": 1, "venomous": 0, "fins": 0, "legs": 0, "tail": 0, "domestic": 0,
     "catsize": 0, "type": 7},
    {"animal name": "sole", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1, "predator": 0,
     "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 0, "fins": 1, "legs": 0, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 4},
    {"animal name": "sparrow", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0,
     "predator": 0, "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 2},
    {"animal name": "squirrel", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 0, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 1},
    {"animal name": "starfish", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 0, "backbone": 0, "breathes": 0, "venomous": 0, "fins": 0, "legs": 5, "tail": 0,
     "domestic": 0, "catsize": 0, "type": 7},
    {"animal name": "stingray", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 1, "fins": 1, "legs": 0, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 4},
    {"animal name": "swan", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 1, "predator": 0,
     "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1, "domestic": 0,
     "catsize": 1, "type": 2},
    {"animal name": "termite", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 0,
     "predator": 0, "toothed": 0, "backbone": 0, "breathes": 1, "venomous": 0, "fins": 0, "legs": 6, "tail": 0,
     "domestic": 0, "catsize": 0, "type": 6},
    {"animal name": "toad", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1, "predator": 0,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 0, "domestic": 0,
     "catsize": 0, "type": 5},
    {"animal name": "tortoise", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 0,
     "predator": 0, "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 3},
    {"animal name": "tuatara", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 0,
     "predator": 1, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 3},
    {"animal name": "tuna", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 1, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 0, "venomous": 0, "fins": 1, "legs": 0, "tail": 1, "domestic": 0,
     "catsize": 1, "type": 4},
    {"animal name": "vampire", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 1, "aquatic": 0,
     "predator": 0, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1,
     "domestic": 0, "catsize": 0, "type": 1},
    {"animal name": "vole", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 0,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 1},
    {"animal name": "vulture", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0,
     "predator": 1, "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 2},
    {"animal name": "wallaby", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0,
     "predator": 0, "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1,
     "domestic": 0, "catsize": 1, "type": 1},
    {"animal name": "wasp", "hair": 1, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0, "predator": 0,
     "toothed": 0, "backbone": 0, "breathes": 1, "venomous": 1, "fins": 0, "legs": 6, "tail": 0, "domestic": 0,
     "catsize": 0, "type": 6},
    {"animal name": "wolf", "hair": 1, "feathers": 0, "eggs": 0, "milk": 1, "airborne": 0, "aquatic": 0, "predator": 1,
     "toothed": 1, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 4, "tail": 1, "domestic": 0,
     "catsize": 1, "type": 1},
    {"animal name": "worm", "hair": 0, "feathers": 0, "eggs": 1, "milk": 0, "airborne": 0, "aquatic": 0, "predator": 0,
     "toothed": 0, "backbone": 0, "breathes": 1, "venomous": 0, "fins": 0, "legs": 0, "tail": 0, "domestic": 0,
     "catsize": 0, "type": 7},
    {"animal name": "wren", "hair": 0, "feathers": 1, "eggs": 1, "milk": 0, "airborne": 1, "aquatic": 0, "predator": 0,
     "toothed": 0, "backbone": 1, "breathes": 1, "venomous": 0, "fins": 0, "legs": 2, "tail": 1, "domestic": 0,
     "catsize": 0, "type": 2}
]
