# Form implementation generated from reading ui file 'LoginWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(642, 498)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(190, 230, 251, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEditLogin = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEditLogin.setObjectName("lineEditLogin")
        self.gridLayout.addWidget(self.lineEditLogin, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout.addWidget(self.lineEditPassword, 1, 2, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(190, 360, 251, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonSignIn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonSignIn.setObjectName("pushButtonSignIn")
        self.horizontalLayout.addWidget(self.pushButtonSignIn)
        self.pushButtonSignUp = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonSignUp.setObjectName("pushButtonSignUp")
        self.horizontalLayout.addWidget(self.pushButtonSignUp)
        self.pushButtonGuest = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonGuest.setObjectName("pushButtonGuest")
        self.horizontalLayout.addWidget(self.pushButtonGuest)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Password:"))
        self.label_2.setText(_translate("Form", "Login:"))
        self.pushButtonSignIn.setText(_translate("Form", "Sign In"))
        self.pushButtonSignUp.setText(_translate("Form", "Sign Up"))
        self.pushButtonGuest.setText(_translate("Form", "Guest"))
